stages:
  - lint

.lint-job:
  image: python:3.12-slim
  stage: lint
  interruptible: true
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - .venv
        - .cache/pip

  before_script:
    - pip install uv
    - uv sync
  variables:
    GIT_STRATEGY: clone
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

mypy:
  extends: .lint-job
  script:
    - uv run mypy .

black:
  extends: .lint-job
  script:
    - uv run black --check .

ruff:
  extends: .lint-job
  script:
    - uv run ruff check .

pytest:
  extends: .lint-job
  script:
    - uv run coverage run
    - uv run coverage report -m
    - uv run coverage xml
  coverage: "/^TOTAL.*\\s(\\d*)/"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
