stages:
  - lint

.lint-job: &lint_job
  image: python:3.10-slim
  stage: lint
  interruptible: true
  cache:
    - key:
        files:
          - pdm.lock
      paths:
        - .venv
        - .cache/pip

  before_script:
    - pip install pdm
    - pdm install
  variables:
    GIT_STRATEGY: clone
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

mypy:
  <<: *lint_job
  script:
    - pdm run mypy .

black:
  <<: *lint_job
  script:
    - pdm run black --check .

ruff:
  <<: *lint_job
  script:
    - pdm run ruff check .

pytest:
  <<: *lint_job
  script:
    - pdm run test --cov-report xml:./tmp/coverage.xml
  coverage: "/^TOTAL.*\\s(\\d*)/"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./tmp/coverage.xml
