version: "3"

vars:
  RUNNER:
    sh: 'echo {{ .RUNNER | default "" }}'
  SOURCES: .

tasks:
  default:
    cmd:
      task: all

  lint:
    desc: Lint python source files
    cmds:
      - "{{.RUNNER}} ruff check {{.SOURCES}}"
      - "{{.RUNNER}} ruff format --check {{.SOURCES}}"

  format:
    desc: Format python source files
    aliases: ["fmt"]
    cmds:
      - "{{.RUNNER}} ruff check --fix {{.SOURCES}}"
      - "{{.RUNNER}} ruff format {{.SOURCES}}"

  typecheck:
    desc: Perform type-checking
    cmd: "{{.RUNNER}} mypy {{.SOURCES}}"

  test:
    desc: Run tests
    cmd: "{{.RUNNER}} coverage run"

  testcov:
    desc: Run tests and generate a coverage report
    cmds:
      - task: test
      - "{{.RUNNER}} coverage report -m"
      - "{{.RUNNER}} coverage xml"

  all:
    desc: Run the standard set of checks performed in CI
    cmds:
      - task: format
      - task: typecheck
      - task: testcov
