name: Publish Docs
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Cache PIP
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: pip-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}
      - name: Install PDM
        run: |
          pip install pdm
          pdm sync --clean
      - run: pdm run mkdocs gh-deploy --force
