name: Test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.11.4
        job:
          - mypy .
          - black --check .
          - ruff check .
          - |
            pdm run coverage run
            pdm run coverage report -m
            pdm run coverage xml

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.pyton-version }}-hashFiles('pdm.lock')
      - name: Install PDM
        run: |
          pip install pdm
          pdm sync --clean

      - run: pdm run ${{ matrix.job }}
