name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.10.17
          - 3.11.12
          - 3.12.10
          - 3.13.3
#          - 3.14
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - run: |
          uv run coverage run
          uv run coverage report -m
          uv run coverage xml
